=pod

=head1 Asciian

The open-source asciiart of alphabets.

=head2 Gallery

=head3 Asciian 16x8

  ################ ################ ################ ################
  ################ ######    ###### #            ### ####         ###
  ################ #####  ##  ##### #  #########  ## ##  ########  ##
  ################ ####  ####  #### #            ### #  #############
  ################ ###          ### #  #########  ## #  #############
  ################ ##  ########  ## #  ##########  # ##  ########  ##
  ################ #  ##########  # #             ## ###          ###
  ################ ################ ################ ################

  ################ ################ ################ ################
  #            ### #             ## #             ## ####         ###
  #  #########  ## #  ############# #  ############# ##  ########  ##
  #  ##########  # #            ### #            ### #  #############
  #  ##########  # #  ############# #  ############# #  ###        ##
  #  ########  ### #  ############# #  ############# ##  #######   ##
  #           #### #             ## #  ############# ###          ###
  ################ ################ ################ ################

  ################ ################ ################ ################
  #  ##########  # #######  ####### #############  # #  #######     #
  #  ##########  # #######  ####### #############  # #  #####    ####
  #              # #######  ####### #############  # #  ##    #######
  #  ##########  # #######  ####### ##  #########  # #     #   ######
  #  ##########  # #######  ####### ##  #########  # #  ######    ###
  #  ##########  # #######  ####### ###           ## #  ########    #
  ################ ################ ################ ################

  ################ ################ ################ ################
  #  ############# #    ######    # #     #######  # ####         ###
  #  ############# #  #  ####  #  # #  ##  ######  # ##  ########  ##
  #  ############# #  ##      ##  # #  ###  #####  # #  ##########  #
  #  ############# #  ####  ####  # #  ####  ####  # #  ##########  #
  #  ############# #  ##########  # #  #####   ##  # ##  ########  ##
  #              # #  ##########  # #  #######     # ###          ###
  ################ ################ ################ ################

  ################ ################ ################ ################
  #             ## ####         ### #             ## ###           ##
  #  ##########  # ##  ########  ## #  ##########  # ##  ############
  #             ## #  ##########  # #             ## ###          ###
  #  ############# #  ######  ##  # #  #######  #### ###########    #
  #  ############# ##  #######   ## #  ########  ### #   #######    #
  #  ############# ###        ##  # #  #########   # ##           ###
  ################ ################ ################ ################

  ################ ################ ################ ################
  #              # #  ##########  # #  ##########  # #  ##########  #
  #######  ####### #  ##########  # ##  ########  ## #  ##########  #
  #######  ####### #  ##########  # ###  ######  ### #  ###    ###  #
  #######  ####### #  ##########  # ####  ####  #### #  ##  ##  ##  #
  #######  ####### ##  ########  ## #####  ##  ##### #  #  ####  #  #
  #######  ####### ###          ### ######    ###### #    ######    #
  ################ ################ ################ ################

  ################ ################ ################
  #   ########   # #   ########   # #              #
  ####  ####  #### ####  ####  #### ##########   ###
  ######    ###### ######    ###### ########   #####
  ######    ###### #######  ####### #####   ########
  ####  ####  #### #######  ####### ###  ###########
  #   ########   # #######  ####### #              #
  ################ ################ ################

=head3 Asciian 15x9

  ############### ############### ############### ###############
  ############### ######   ###### #           ### ####       ####
  ############### #####  #  ##### #  ########  ## ##  #######  ##
  ############### ####  ###  #### #  #########  # #  #########  #
  ############### ###  #####  ### #            ## #  ############
  ############### ##           ## #  ########   # #  #########  #
  ############### #  #########  # #  #########  # ##  #######  ##
  ############### #  #########  # #            ## ###        ####
  ############### ############### ############### ###############

  ############### ############### ############### ###############
  #           ### #             # #             # ####       ####
  #  ########  ## #  ############ #  ############ ##  #######  ##
  #  #########  # #  ############ #  ############ #  #########  #
  #  #########  # #           ### #           ### #  ############
  #  #########  # #  ############ #  ############ #  ####       #
  #  ########  ## #  ############ #  ############ ##  #######  ##
  #          #### #             # #  ############ ###        ####
  ############### ############### ############### ###############

  ############### ############### ############### ###############
  #  #########  # ######  ####### ############  # #  ########   #
  #  #########  # ######  ####### ############  # #  #####   ####
  #  #########  # ######  ####### ############  # #  ##   #######
  #             # ######  ####### ############  # #     #########
  #  #########  # ######  ####### #  #########  # #  ##   #######
  #  #########  # ######  ####### #  #########  # #  #####   ####
  #  #########  # ######  ####### ##           ## #  ########   #
  ############### ############### ############### ###############

  ############### ############### ############### ###############
  #  ############ #    ######   # #    #######  # ####       ####
  #  ############ #  #  ###  #  # #  #  ######  # ##  #######  ##
  #  ############ #  ##  #  ##  # #  ##  #####  # #  #########  #
  #  ############ #  ###   ###  # #  ###  ####  # #  #########  #
  #  ############ #  #### ####  # #  ####  ###  # #  #########  #
  #  ############ #  #########  # #  ######  #  # ##  #######  ##
  #             # #  #########  # #  #######    # ###        ####
  ############### ############### ############### ###############

  ############### ############### ############### ###############
  #            ## ####       #### #            ## ##           ##
  #  #########  # ##  #######  ## #  #########  # #  #########  #
  #  #########  # #  #########  # #  #########  # #  ############
  #            ## #  #####  ##  # #            ## #             #
  #  ############ #  ######  #  # #  ####   ##### ############  #
  #  ############ ##  ######   ## #  ######   ### #  #########  #
  #  ############ ###        #  # #  ########   # ##           ##
  ############### ############### ############### ###############

  ############### ############### ############### ###############
  #             # #  #########  # #  #########  # #  #########  #
  ######  ####### #  #########  # #  #########  # #  #########  #
  ######  ####### #  #########  # ##  #######  ## #  #########  #
  ######  ####### #  #########  # ###  #####  ### #  ###  ####  #
  ######  ####### #  #########  # ####  ###  #### #  ##    ###  #
  ######  ####### ##  #######  ## #####  #  ##### #  #  ###  #  #
  ######  ####### ###         ### ######   ###### #    #####    #
  ############### ############### ############### ###############

  ############### ############### ###############
  #  #########  # #  #########  # #             #
  ###  #####  ### ###  #####  ### ##########   ##
  #####  #  ##### #####  #  ##### ########   ####
  ####### ####### ######  ####### ######   ######
  #####  #  ##### ######  ####### ####   ########
  ###  ####  #### ######  ####### ##   ##########
  #  ########  ## ######  ####### #             #
  ############### ############### ###############

=head2 License

(c) 2023 TANIGUCHI Masaya
This font is licensed under the CC-BY 4.0 License.

=cut
